### ISSUE TITLE
Method not found when creating time series add

### ISSUE THREAD

**Issue by geoHeil** [twosigma/flint#53]
`  val tsRdd = TimeSeriesRDD.fromDF(dataFrame = df)(isSorted = true, timeUnit = MILLISECONDS)`

throws

```
scala> val tsRdd = TimeSeriesRDD.fromDF(dataFrame = cellFeed)(isSorted = true, timeUnit = MILLISECONDS)
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.plans.physical.ClusteredDistribution$.apply$default$2()Lscala/Option;
  at com.twosigma.flint.timeseries.TimeSeriesStore$.isClustered(TimeSeriesStore.scala:149)
  at com.twosigma.flint.timeseries.TimeSeriesStore$.apply(TimeSeriesStore.scala:64)
  at com.twosigma.flint.timeseries.TimeSeriesRDD$.fromDFWithPartInfo(TimeSeriesRDD.scala:509)
  at com.twosigma.flint.timeseries.TimeSeriesRDD$.fromDF(TimeSeriesRDD.scala:304)
  ... 52 elided

```
on spark 2.2 when trying to create the initial RDD.

Minimal reproducible sample:
```
import spark.implicits._
  import com.twosigma.flint.timeseries.TimeSeriesRDD
  import scala.concurrent.duration._
  val df = Seq((1, 1, 1L), (2, 3, 1L), (1, 4, 2L), (2, 2, 2L)).toDF("id", "value", "time")
  val tsRdd = TimeSeriesRDD.fromDF(dataFrame = df)(isSorted = true, timeUnit = MILLISECONDS)
```
on spark 2.2 via HDP 2.6.4

**Comment by geoHeil** [comment]
Regular spark 2.3.2 works fine, regular spark 2.2.1 also fails with above exception.

**Comment by geoHeil** [comment]
When creating a custom build like https://github.com/geoHeil/flint/tree/flint-spark-2.2 the basic example works again with spark 2.2

**Comment by icexelloss** [comment]
Hi!

The current flint version only supports Spark 2.3.
