### ISSUE TITLE
pyspark 2.4 support

### ISSUE THREAD

**Issue by mattomatic** [twosigma/flint#63]
Does this library currently work with spark 2.4?

**Comment by icexelloss** [comment]
We have not tried it with Spark 2.4 yet.

**Comment by andompesta** [comment]
It does not work wit 2.3.2 as well

**Comment by icexelloss** [comment]
what issues do you see with 2.3.2? Internally we use flint with 2.3.2
without issues.

**Comment by mattomatic** [comment]
https://github.com/twosigma/flint/pull/64

Managed these changes to get it to build under spark 2.4

**Comment by kunalsingh09** [comment]
Hi I am trying to follow the example from here 
https://github.com/twosigma/flint/blob/master/example/Flint%20Example.ipynb

Here is my example 
booking = spark.read.option('header', True).option('inferSchema', True).csv(CSV_FILE)
booking2 = flintContext.read.dataframe(booking)

I see the below error 
TypeError                                 Traceback (most recent call last)
~/anaconda/envs/featuretool/lib/python3.7/site-packages/ts/flint/java.py in new_reader(self)
     37         try:
---> 38             return utils.jvm(self.sc).com.twosigma.flint.timeseries.io.read.TSReadBuilder()
     39         except TypeError:

TypeError: 'JavaPackage' object is not callable

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-76-002bf54640f7> in <module>
----> 1 booking2 = flintContext.read.dataframe(booking)

~/anaconda/envs/featuretool/lib/python3.7/site-packages/ts/flint/context.py in read(self)
     82         '''
     83 
---> 84         return readwriter.TSDataFrameReader(self)

~/anaconda/envs/featuretool/lib/python3.7/site-packages/ts/flint/readwriter.py in __init__(self, flintContext)
     49         self._sqlContext = self._flintContext._sqlContext
     50         self._jpkg = java.Packages(self._sc)
---> 51         self._reader = self._jpkg.new_reader()
     52         self._parameters = self._reader.parameters()
     53 

~/anaconda/envs/featuretool/lib/python3.7/site-packages/ts/flint/java.py in new_reader(self)
     38             return utils.jvm(self.sc).com.twosigma.flint.timeseries.io.read.TSReadBuilder()
     39         except TypeError:
---> 40             return utils.jvm(self.sc).com.twosigma.flint.timeseries.io.read.ReadBuilder()
     41 
     42     @property

TypeError: 'JavaPackage' object is not callable.

I don't see in the example if flint jar has been passed in notebook but I also tried building and passing  something like below but it did not help. I am running on spark-2.4.0-bin-hadoop2.7
SUBMIT_ARGS = "\
--master yarn \
--deploy-mode client \
--jar /Users/kkum25/Downloads/flint-master/target/flint-assembly-0.6.0-SNAPSHOT.jar \
pyspark-shell"

# Spark "SPARK_HOME" for local this code and children
#os.environ["SPARK_HOME"] = "/usr/lib/spark"
#os.environ["PYSPARK_PYTHON"] = "./MYENV/py3.6/bin/python"
os.environ["PYSPARK_SUBMIT_ARGS"] = SUBMIT_ARGS

findspark.init()

from pyspark.sql import SparkSession
spark = SparkSession \
.builder \
.appName("packages test") \
.enableHiveSupport() \
.getOrCreate()

**Comment by kunalsingh09** [comment]
I am running on spark-2.4.0-bin-hadoop2.7 and seeing the below error. Any idea ?
>>> from ts.flint import windows
>>> sp500_previous_day_return = sp500_return.shiftTime(windows.future_absolute_time('1day')).toDF('time', 'previous_day_return')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kkum25/anaconda/envs/featuretool/lib/python3.7/site-packages/ts/flint/dataframe.py", line 1591, in shiftTime
    tsrdd = self.timeSeriesRDD.shift(window._jwindow(self._sc))
  File "/Users/kkum25/anaconda/envs/featuretool/lib/python3.7/site-packages/ts/flint/dataframe.py", line 154, in timeSeriesRDD
    self._jdf, self._is_sorted, self._junit, self._time_column)
  File "/usr/local/Cellar/apache-spark/2.2.1/libexec/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/local/Cellar/apache-spark/2.2.1/libexec/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/local/Cellar/apache-spark/2.2.1/libexec/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o124.fromDF.
: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.plans.physical.ClusteredDistribution$.apply$default$2()Lscala/Option;
	at com.twosigma.flint.timeseries.TimeSeriesStore$.isClustered(TimeSeriesStore.scala:149)
	at com.twosigma.flint.timeseries.TimeSeriesStore$.apply(TimeSeriesStore.scala:64)
	at com.twosigma.flint.timeseries.TimeSeriesRDD$.fromDFWithPartInfo(TimeSeriesRDD.scala:509)
	at com.twosigma.flint.timeseries.TimeSeriesRDD$.fromDF(TimeSeriesRDD.scala:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kunalsingh09** [comment]
> #64
> 
> Managed these changes to get it to build under spark 2.4

before this change what issue you were seeing ?

**Comment by luzlab** [comment]
Is there any blockers to merging this in? I'd like to use Flint on Databricks but I don't see any compatible versions of Spark being offered (2.2.1 or 2.4.[0,1,2] are only versions of Spark currently available).

I think this is a great project and would love to help mature it!

**Comment by dgrnbrg** [comment]
I have been successfully using @mattomatic's changes to run on Spark 2.4.

**Comment by prabhash17** [comment]
@icexelloss Does this library work with spark 2.2.x  version?
